//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Report_RDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public int Id { get; set; }
        public string Descripcon { get; set; }
        public string Moneda { get; set; }
    }
}
